replies = ['It is certain.',
                  'It is decidedly so.',
                  'Without a doubt.',
                  'Yes - definitely.',
                  'You may rely on it.',
                  'As I see it, yes.',
                  'Most likely.',
                  'Outlook good.',
                  'Yes.',
                  'Signs point to yes.',
                  'Reply hazy, try again.',
                  'Ask again later.',
                  'Better not tell you now.',
                  'Cannot predict now.',
                  'Concentrate and ask again.',
                  'Do not count on it.',
                  'My reply is no.',
                  'Ask Hybrid about it',
                  'Ask NullCube about it',
                  'My sources say no.',
                  'Outlook not so good.',
                  'Very doubtful.']
