wreplies = [
'You applied for a job at a large tech company, You did not get the job, but you found some money on the streets afterwards!', 
'You have successfully taken out your target, good job Agent 47, you now have a hot date, here is some money for your hard work!',
'You manage to pull off an amazing stunt, and you post it on YouTube. Your video goes viral, earning you a bunch of money!', 
'No one gets out alive.... Except you, who also somehow managed to get some money in the process!', 
'You find some money in your bank account. Turns out it was not empty after all!', 
'Your girlfriend turned into the moon, but your friends took pity on you and gave you some money!', 
'You win a prize in a Pro-Bending tournament!', 
'You stream osu! on twitch and you get really good plays. You earn some money from your subscriptions!', 
'You streamed yourself reacting to videos. Even though you did not really do anything you got some donations anyways!', 
'You try out programming, you make a discord bot that is used in thousands of servers. Well done, you get paid for your efforts!', 
'You take up animation, you send in an application to Studio Bones, they hire you and say that your animation is some of the best they have seen. They place you on the My Hero Academia season 5 animation team, you get paid for your efforts!', 
'Some money falls out of the sky and hits you on the head! Ouch...', 
'You pleased the admins by playing Djazz at your last party and they gave you some tips!', 
'You get hired for a role in Marvels Iron Man 4. The movie should not exist, because Tony Stark is dead… Right? You get paid for your hassle!',
'You what now? Fine...',
]